"use client";

import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import { Plus, UserX, UserCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { auth, db } from "@/lib/firebase";
import type { AppUser, UserRole } from "@/lib/types";
import Modal from "./Modal";

export default function UserManager(){
 const [users,setUsers]=useState<AppUser[]>([]); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [form,setForm]=useState({name:"",email:"",cpf:"",role:"atendente" as UserRole});
 useEffect(()=>onSnapshot(query(collection(db,"users"),orderBy("name")),s=>setUsers(s.docs.map(d=>({uid:d.id,...d.data()} as AppUser)))),[]);
 async function token(){return await auth.currentUser?.getIdToken()}
 async function create(){setError(""); if(!form.name||!form.email||form.cpf.replace(/\D/g,"").length!==11)return setError("Preencha nome, e-mail e um CPF com 11 dígitos.");setLoading(true);try{const res=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await token()}`},body:JSON.stringify({...form,cpf:form.cpf.replace(/\D/g,"")})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Erro ao criar usuário");setForm({name:"",email:"",cpf:"",role:"atendente"});setOpen(false)}catch(e){setError(e instanceof Error?e.message:"Erro")}finally{setLoading(false)}}
 async function toggle(u:AppUser){const res=await fetch(`/api/admin/users/${u.uid}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${await token()}`},body:JSON.stringify({active:!u.active})});if(!res.ok)alert("Não foi possível alterar o acesso.")}
 return <><div className="panel"><div className="panel-head"><h2>Usuários com acesso</h2><button className="btn primary" onClick={()=>setOpen(true)}><Plus size={16}/> Novo usuário</button></div><div className="table-wrap"><table className="table"><thead><tr><th>Nome</th><th>E-mail</th><th>CPF</th><th>Perfil</th><th>Status</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.uid}><td><strong>{u.name}</strong></td><td>{u.email}</td><td>{u.cpfLast4?`***.***.***-${u.cpfLast4}`:"—"}</td><td><span className={`pill ${u.role}`}>{u.role}</span></td><td><span className={`pill ${u.active?"active":""}`}>{u.active?"Ativo":"Bloqueado"}</span></td><td><button className="btn" onClick={()=>toggle(u)}>{u.active?<><UserX size={15}/> Bloquear</>:<><UserCheck size={15}/> Ativar</>}</button></td></tr>)}</tbody></table></div></div>{open&&<Modal title="Criar usuário" onClose={()=>setOpen(false)} footer={<><button className="btn" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn primary" onClick={create} disabled={loading}>{loading?"Criando...":"Criar usuário"}</button></>}><div className="stack">{error&&<div className="error">{error}</div>}<div className="field"><label>Nome completo</label><input className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>E-mail de acesso</label><input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="field"><label>CPF — senha de acesso</label><input className="input" inputMode="numeric" value={form.cpf} onChange={e=>setForm({...form,cpf:e.target.value.replace(/\D/g,"").slice(0,11)})}/><small style={{color:"#777"}}>O CPF não será gravado em texto puro no Firestore.</small></div><div className="field"><label>Perfil</label><select className="select" value={form.role} onChange={e=>setForm({...form,role:e.target.value as UserRole})}><option value="admin">Administrador</option><option value="atendente">Atendente</option><option value="consulta">Consulta</option></select></div></div></Modal>}</>
}
